--//고객 테이블
CREATE TABLE CUSTOMER (
CST_ID VARCHAR(15) PRIMARY KEY,
CST_PW VARCHAR(15) NOT NULL,
CST_NAME VARCHAR(20) NOT NULL,
CST_NUM VARCHAR(20) NOT NULL)

--//날짜 테이블
CREATE TABLE DATES (
M_D VARCHAR(10) PRIMARY KEY)

--//관리자 테이블
CREATE TABLE MANAGER (
MNG_ID VARCHAR(15) PRIMARY KEY,
MNG_PW VARCHAR(15) NOT NULL,
MNG_ONUM VARCHAR(20) NOT NULL,
MNG_OWN VARCHAR(20) NOT NULL,
MNG_BRN VARCHAR(20) NOT NULL)

--//직급에 따른 추가 금액 테이블
CREATE TABLE PRICE (
PR_PST VARCHAR(15) PRIMARY KEY,
PR_ADD NUMBER(10) NOT NULL)

--//시술 서비스 테이블
CREATE TABLE SERVICE (
SV_NAME VARCHAR(20) PRIMARY KEY,
SV_PRICE NUMBER(10) NOT NULL,
SV_TIME NUMBER(5) NOT NULL)

--//시간대 테이블
CREATE TABLE TIMES ( H_TIME VARCHAR(10) PRIMARY KEY)

--//디자이너 테이블(금액 테이블 참조)
CREATE TABLE DESIGNER (
DSR_CODE VARCHAR(15) PRIMARY KEY,
DSR_NAME VARCHAR(20) NOT NULL,
DSR_CAR NUMBER(5) NOT NULL,
DSR_PST VARCHAR(15) NOT NULL,
CONSTRAINT DSR_PST_FK FOREIGN KEY (DSR_PST) REFERENCES PRICE(PR_PST));

--//디자이너 스케줄 테이블(날짜, 시간, 디자이너 테이블 참조)
CREATE TABLE DSR_SCHEDULE (
DSRSCH_CODE VARCHAR(10) PRIMARY KEY,
DSRSCH_DCODE VARCHAR(15) NOT NULL,
DSRSCH_TIME VARCHAR(10) NOT NULL,
DSRSCH_DATE VARCHAR(10) NOT NULL,
CONSTRAINT DSRSCH_DCODE_FK FOREIGN KEY(DSRSCH_DCODE) REFERENCES DESIGNER(DSR_CODE),
CONSTRAINT DSRSCH_TIME_FK FOREIGN KEY(DSRSCH_TIME) REFERENCES TIMES(H_TIME),
CONSTRAINT DSRSCH_DATE_FK FOREIGN KEY(DSRSCH_DATE) REFERENCES DATES(M_D));
CREATE SEQUENCE SEQ_DSRSCH_CODE;

--//예약 스케줄 테이블(디자이너, 시간, 날짜 테이블 참조)
CREATE TABLE RSV_SCHEDULE (
RSVSCH_CODE VARCHAR(10) PRIMARY KEY,
RSVSCH_DSRCODE VARCHAR(15) NOT NULL,
RSVSCH_TIME VARCHAR(10) NOT NULL,
RSVSCH_DATE VARCHAR(10) NOT NULL,
CONSTRAINT RSVSCH_DSRCODE_FK FOREIGN KEY(RSVSCH_DSRCODE) REFERENCES DESIGNER(DSR_CODE),
CONSTRAINT RSVSCH_TIME_FK FOREIGN KEY(RSVSCH_TIME) REFERENCES TIMES(H_TIME),
CONSTRAINT RSVSCH_DATE_FK FOREIGN KEY(RSVSCH_DATE) REFERENCES DATES(M_D));

--//예약 테이블(고객, 시술서비스, 예약스케줄 참조)
CREATE TABLE RESERVATION (
RSV_NUM NUMBER(10) PRIMARY KEY,
RSV_DATE VARCHAR(10) NOT NULL,
RSV_GEN VARCHAR(10) NOT NULL,
RSV_COST NUMBER(10) NOT NULL,
RSV_CST_ID VARCHAR(15) NOT NULL,
RSV_SV_NAME VARCHAR(20) NOT NULL,
RSV_SCH_CODE VARCHAR(10) NOT NULL,
CONSTRAINT RSV_CST_ID_FK FOREIGN KEY(RSV_CST_ID) REFERENCES CUSTOMER(CST_ID),
CONSTRAINT RSV_SV_NAME_FK FOREIGN KEY(RSV_SV_NAME) REFERENCES SERVICE(SV_NAME),
CONSTRAINT RSV_SCH_CODE_FK FOREIGN KEY(RSV_SCH_CODE) REFERENCES RSV_SCHEDULE(RSVSCH_CODE));
CREATE SEQUENCE SEQ_RSV_NUM;


--//날짜 테이블에 데이터 삽입
INSERT INTO DATES VALUES ('7/1'); 
INSERT INTO DATES VALUES ('7/2');
INSERT INTO DATES VALUES ('7/3');
INSERT INTO DATES VALUES ('7/4');
INSERT INTO DATES VALUES ('7/5');
INSERT INTO DATES VALUES ('7/6'); 
INSERT INTO DATES VALUES ('7/7');
INSERT INTO DATES VALUES ('7/8');
INSERT INTO DATES VALUES ('7/9');
INSERT INTO DATES VALUES ('7/10');
INSERT INTO DATES VALUES ('7/11'); 
INSERT INTO DATES VALUES ('7/12');
INSERT INTO DATES VALUES ('7/13');
INSERT INTO DATES VALUES ('7/14');
INSERT INTO DATES VALUES ('7/15');
INSERT INTO DATES VALUES ('7/16'); 
INSERT INTO DATES VALUES ('7/17');
INSERT INTO DATES VALUES ('7/18');
INSERT INTO DATES VALUES ('7/19');
INSERT INTO DATES VALUES ('7/20');
INSERT INTO DATES VALUES ('7/21'); 
INSERT INTO DATES VALUES ('7/22');
INSERT INTO DATES VALUES ('7/23');
INSERT INTO DATES VALUES ('7/24');
INSERT INTO DATES VALUES ('7/25');
INSERT INTO DATES VALUES ('7/26'); 
INSERT INTO DATES VALUES ('7/27');
INSERT INTO DATES VALUES ('7/28');
INSERT INTO DATES VALUES ('7/29');
INSERT INTO DATES VALUES ('7/30');
INSERT INTO DATES VALUES ('7/31');



--//시간대 테이블 데이터 삽입
INSERT INTO TIMES VALUES ('10:00');
INSERT INTO TIMES VALUES ('11:00');
INSERT INTO TIMES VALUES ('12:00');
INSERT INTO TIMES VALUES ('13:00');
INSERT INTO TIMES VALUES ('14:00');
INSERT INTO TIMES VALUES ('15:00');
INSERT INTO TIMES VALUES ('16:00');
INSERT INTO TIMES VALUES ('17:00');
INSERT INTO TIMES VALUES ('18:00');
INSERT INTO TIMES VALUES ('19:00');

--//시술 서비스 테이블 데이터 삽입
INSERT INTO SERVICE VALUES('남성컷',10000,1);
INSERT INTO SERVICE VALUES('남성펌',40000,2);
INSERT INTO SERVICE VALUES('남성매직',40000,2);
INSERT INTO SERVICE VALUES('남성셋팅',50000,2);
INSERT INTO SERVICE VALUES('남성염색',40000,2);
INSERT INTO SERVICE VALUES('남성매직셋팅',60000,3);
INSERT INTO SERVICE VALUES('여성컷',20000,1);
INSERT INTO SERVICE VALUES('여성펌',50000,2);
INSERT INTO SERVICE VALUES('여성매직',50000,2);
INSERT INTO SERVICE VALUES('여성셋팅',70000,2);
INSERT INTO SERVICE VALUES('여성매직셋팅',90000,3);
INSERT INTO SERVICE VALUES('여성염색',50000,2);

//관리자 테이블 테스트 데이터 삽입
--INSERT INTO MANAGER VALUES('mngidTest', 'mngpwTest', '1234', 'mngnameTest', '테스트');

--//직급에 따른 추가 금액 테이블 데이터 삽입
INSERT INTO PRICE VALUES('Director',20000);
INSERT INTO PRICE VALUES('TopDesigner',10000);
INSERT INTO PRICE VALUES('Designer',5000);
INSERT INTO PRICE VALUES('Intern',0);

--//디자이너 테이블 데이터 삽입
INSERT INTO DESIGNER VALUES('DSR0','노송이',8,'Director');
INSERT INTO DESIGNER VALUES('DSR1','김승현',7,'TopDesigner');
INSERT INTO DESIGNER VALUES('DSR2','이시면',2,'Intern');
INSERT INTO DESIGNER VALUES('DSR3','김준철',3,'Designer');
INSERT INTO DESIGNER VALUES('DSR4','우도희',5,'TopDesigner');

select * from DSR_SCHEDULE;
select * from RSV_SCHEDULE;
commit
select * from reservation;

drop table RESERVATION;
drop table RSV_SCHEDULE;
drop table DSR_SCHEDULE;
drop table DESIGNER;
drop table TIMES;
drop TABLE DATES;
drop table SERVICE;
drop table price;
drop TABLE MANAGER;
drop TABLE CUSTOMER;
drop sequence seq_rsv_num;
drop SEQUENCE SEQ_DSRSCH_CODE;

select * from manager
select * from service
